import { writable } from "svelte/store";
import type { AppLanguage } from "$lib/api/types";

export type ResolvedLocale = "zh-CN" | "en" | "ja";

const translations = {
  "zh-CN": {
    waitingPlayback: "等待播放...", unknownArtist: "未知艺术家", mediaPlayer: "音乐播放器",
    dragWindow: "拖动窗口", unpin: "取消置顶", pin: "置顶", close: "关闭",
    previous: "上一首", next: "下一首", play: "播放", pause: "暂停", playbackControls: "播放控制",
    shuffleOn: "开启随机播放", shuffleOff: "关闭随机播放", repeatMode: "循环模式：{mode}",
    playbackProgress: "播放进度 {percent}%", seekProgress: "调整播放进度", dynamicIsland: "灵动岛，点击切换展开状态",
    openPlayer: "打开当前播放器", volume: "系统音量", muted: "静音", idleInfo: "空闲信息",
    previousItem: "上一项", nextItem: "下一项", resumeCarousel: "继续轮播", pauseCarousel: "暂停轮播", toggleFloating: "切换悬浮窗", timer: "倒计时", remainingTime: "剩余时间", startTimer: "开始倒计时", addMinute: "增加 1 分钟", addFiveMinutes: "增加 5 分钟", pauseTimer: "暂停倒计时", resumeTimer: "继续倒计时", cancelTimer: "取消倒计时",
    studioIntro: "集中设置灵动岛的外观、播放和系统行为。", currentMusic: "当前音乐", simulated: "模拟场景", browserDemo: "浏览器演示", previewLabel: "灵动岛白底预览", previewState: "预览状态", compact: "收起", hover: "悬停", expanded: "展开", hidden: "隐藏", shoulderShort: "凹肩", audioSpectrum: "六段音频频谱", systemDefault: "系统默认", islandLayout: "灵动岛布局", shape: "形态", shapeHint: "普通悬浮或 iPhone X 式贴边",
    theme: "材质主题", themeHint: "保持黑色基底，只给表面增加克制的实时光泽。", themeOriginal: "原始", themeShaderDial: "Shader Dial", themeAlbumReactive: "专辑响应", floating: "悬浮", attached: "贴边", screenEdge: "屏幕边缘", screenEdgeHint: "展开后仍保持连接", floatingBackground: "悬浮窗填充色", floatingBackgroundHint: "关闭跟随封面颜色时使用的固定颜色", useAlbumColor: "跟随专辑封面颜色", useAlbumColorHint: "从封面代表色生成纵向渐变背景", top: "上", right: "右", bottom: "下", left: "左",
    screenTop: "屏幕顶部", screenRight: "屏幕右侧", screenBottom: "屏幕底部", screenLeft: "屏幕左侧", edgePosition: "沿边位置", center: "居中显示",
    compactLength: "收起长度", shoulder: "贴边凹肩", expandedRadius: "展开圆角", language: "语言", systemLanguage: "跟随系统", chinese: "简体中文", english: "English", japanese: "日本語",
    font: "字体", appFont: "全应用字体", fontHint: "应用于设置页、灵动岛与悬浮播放器。", mediaScene: "媒体场景", noCover: "无封面", longTitle: "长标题", followMusic: "恢复跟随当前音乐",
    spectrum: "频谱", showSpectrum: "显示频谱", showSpectrumHint: "在播放状态中显示六段动态频谱", animationSource: "动画来源", animationSourceHint: "实时音频或随机动画", realtime: "随音乐跳动", random: "随机跳动",
    players: "播放器", refreshPlayers: "刷新播放器", playersHint: "只显示已勾选播放器，并按从上到下的顺序选择。", select: "选择 {name}", playingNow: "正在播放", detected: "已检测", offline: "当前离线", moveUp: "上移", moveDown: "下移", noSessions: "未检测到 Windows 媒体会话",
    idleContent: "无播放器时内容", enableIdle: "启用空闲轮播", enableIdleHint: "仅在灵动岛没有匹配播放器时显示", interval: "切换间隔", seconds: "{value} 秒", idleInterval: "空闲内容切换间隔", enableItem: "启用{name}", customText: "自定义文本", deleteCustom: "删除自定义文本", addCustom: "添加文本或颜文字",
    clock: "时间", date: "日期", weather: "天气", network: "实时网速", cpu: "CPU", memory: "内存", battery: "电量",
    weatherCity: "天气城市", cityExample: "例如：上海", searchCity: "搜索城市", currentCity: "当前：{name}", weatherSource: "天气数据由 Open-Meteo 提供。", searching: "正在搜索…", noCity: "没有找到匹配城市", weatherFailed: "城市搜索失败，请检查网络", citySaved: "已保存城市",
    mediaFeatures: "媒体增强", hdCover: "高清专辑封面", hdCoverHint: "自动匹配并缓存更清晰的封面", mvPlayback: "30 秒 MV 循环", mvPlaybackHint: "匹配 Apple Music 预览并在悬浮窗静音循环播放",
    appBehavior: "应用行为", alwaysOnTop: "始终置顶", alwaysOnTopHint: "让岛体保持在工作流上方", autoStart: "开机启动", autoStartHint: "登录 Windows 后自动运行", monitor: "显示器", primaryMonitor: "主显示器",
    capture: "截图与捕获", captureHint: "以下开关同时作用于灵动岛和悬浮窗，捕获结束后自动恢复。", hideScreenshot: "截图时隐藏", hideScreenshotHint: "响应 Print Screen 与 Win + Shift + S", hideRecording: "录屏时隐藏", hideRecordingHint: "通过 Windows 内容保护从录制画面排除", hideFullscreen: "全屏游戏时隐藏", hideFullscreenHint: "检测到无边框全屏应用后向边缘收起", hideShare: "屏幕共享时隐藏", hideShareHint: "通过 Windows 内容保护从共享画面排除",
    tools: "工具", openFloating: "打开悬浮播放器", resetFloating: "复位悬浮窗", clearCache: "清理图片与 MV 缓存", clearing: "正在清理…", cacheCleared: "图片与 MV 缓存已清理", clearFailed: "清理失败，请稍后重试",
    featureTools: "功能按钮", featureToolsHint: "选择展开灵动岛时显示哪些工具。", floatingTool: "悬浮播放器", volumeTool: "系统音量", timerTool: "倒计时",
  },
  en: {
    waitingPlayback: "Waiting for playback...", unknownArtist: "Unknown artist", mediaPlayer: "Music player", dragWindow: "Move window", unpin: "Unpin", pin: "Pin on top", close: "Close", previous: "Previous", next: "Next", play: "Play", pause: "Pause", playbackControls: "Playback controls", shuffleOn: "Enable shuffle", shuffleOff: "Disable shuffle", repeatMode: "Repeat mode: {mode}", playbackProgress: "Playback progress {percent}%", seekProgress: "Seek playback", dynamicIsland: "Dynamic Island; click to expand or collapse", openPlayer: "Open current player", volume: "System volume", muted: "Muted", idleInfo: "At a glance", previousItem: "Previous item", nextItem: "Next item", resumeCarousel: "Resume rotation", pauseCarousel: "Pause rotation", toggleFloating: "Toggle floating player", timer: "Timer", remainingTime: "Remaining", startTimer: "Start timer", addMinute: "Add 1 minute", addFiveMinutes: "Add 5 minutes", pauseTimer: "Pause timer", resumeTimer: "Resume timer", cancelTimer: "Cancel timer",
    studioIntro: "Configure the island's appearance, playback, and system behavior.", currentMusic: "Live music", simulated: "Simulation", browserDemo: "Browser demo", previewLabel: "Dynamic Island preview on white", previewState: "Preview state", compact: "Compact", hover: "Hover", expanded: "Expanded", hidden: "Hidden", shoulderShort: "shoulder", audioSpectrum: "Six-band audio spectrum", systemDefault: "System default", islandLayout: "Island layout", shape: "Shape", shapeHint: "Floating or attached in the iPhone X style", theme: "Material theme", themeHint: "Keep the black base and add a restrained, live surface sheen.", themeOriginal: "Original", themeShaderDial: "Shader Dial", themeAlbumReactive: "Album reactive", floating: "Floating", attached: "Attached", screenEdge: "Screen edge", screenEdgeHint: "Stay connected while expanded", floatingBackground: "Floating player fill", floatingBackgroundHint: "Fallback color when album artwork is not used", useAlbumColor: "Follow album artwork color", useAlbumColorHint: "Build a vertical gradient from the artwork's representative color", top: "Top", right: "Right", bottom: "Bottom", left: "Left", screenTop: "Top edge", screenRight: "Right edge", screenBottom: "Bottom edge", screenLeft: "Left edge", edgePosition: "Position along edge", center: "Center", compactLength: "Compact length", shoulder: "Edge shoulder", expandedRadius: "Expanded radius", language: "Language", systemLanguage: "Use system language", chinese: "简体中文", english: "English", japanese: "日本語", font: "Typography", appFont: "App font", fontHint: "Used by Studio, the island, and the floating player.", mediaScene: "Media scene", noCover: "No artwork", longTitle: "Long title", followMusic: "Follow current music", spectrum: "Spectrum", showSpectrum: "Show spectrum", showSpectrumHint: "Show six animated bars during playback", animationSource: "Animation source", animationSourceHint: "Live audio or generated motion", realtime: "Live audio", random: "Generated", players: "Players", refreshPlayers: "Refresh players", playersHint: "Only checked players appear; priority follows this order.", select: "Select {name}", playingNow: "Playing", detected: "Detected", offline: "Offline", moveUp: "Move up", moveDown: "Move down", noSessions: "No Windows media sessions detected",
    idleContent: "When no player is active", enableIdle: "Rotate idle content", enableIdleHint: "Shown only when no matching player is available", interval: "Rotation interval", seconds: "{value} sec", idleInterval: "Idle content rotation interval", enableItem: "Enable {name}", customText: "Custom text", deleteCustom: "Delete custom text", addCustom: "Add text or kaomoji", clock: "Time", date: "Date", weather: "Weather", network: "Network speed", cpu: "CPU", memory: "Memory", battery: "Battery", weatherCity: "Weather city", cityExample: "e.g. Shanghai", searchCity: "Search cities", currentCity: "Current: {name}", weatherSource: "Weather data by Open-Meteo.", searching: "Searching…", noCity: "No matching city found", weatherFailed: "City search failed. Check your connection.", citySaved: "City saved",
    mediaFeatures: "Media enhancements", hdCover: "High-resolution artwork", hdCoverHint: "Match and cache clearer album artwork", mvPlayback: "30-second MV loop", mvPlaybackHint: "Match an Apple Music preview and loop it silently in the floating player", appBehavior: "App behavior", alwaysOnTop: "Always on top", alwaysOnTopHint: "Keep the island above your workspace", autoStart: "Launch at startup", autoStartHint: "Run after signing in to Windows", monitor: "Display", primaryMonitor: "Primary display", capture: "Capture privacy", captureHint: "These settings apply to both surfaces and restore them when capture ends.", hideScreenshot: "Hide during screenshots", hideScreenshotHint: "Respond to Print Screen and Win + Shift + S", hideRecording: "Hide during recording", hideRecordingHint: "Use Windows content protection to exclude the app", hideFullscreen: "Hide in full-screen games", hideFullscreenHint: "Retract when a borderless full-screen app is detected", hideShare: "Hide during screen sharing", hideShareHint: "Use Windows content protection to exclude the app", tools: "Tools", openFloating: "Open floating player", resetFloating: "Reset floating window", clearCache: "Clear artwork and MV cache", clearing: "Clearing…", cacheCleared: "Artwork and MV cache cleared", clearFailed: "Could not clear the cache. Try again.",
    featureTools: "Feature buttons", featureToolsHint: "Choose which tools appear when the island expands.", floatingTool: "Floating player", volumeTool: "System volume", timerTool: "Timer",
  },
  ja: {
    theme: "マテリアルテーマ", themeHint: "黒いベースを保ち、控えめなリアルタイムの光沢を加えます。", themeOriginal: "オリジナル", themeShaderDial: "Shader Dial", themeAlbumReactive: "アルバム連動",
    waitingPlayback: "再生を待機中...", unknownArtist: "不明なアーティスト", mediaPlayer: "ミュージックプレーヤー", dragWindow: "ウィンドウを移動", unpin: "固定を解除", pin: "最前面に固定", close: "閉じる", previous: "前の曲", next: "次の曲", play: "再生", pause: "一時停止", playbackControls: "再生コントロール", shuffleOn: "シャッフルをオン", shuffleOff: "シャッフルをオフ", repeatMode: "リピート：{mode}", playbackProgress: "再生位置 {percent}%", seekProgress: "再生位置を変更", dynamicIsland: "Dynamic Island（クリックで展開・収納）", openPlayer: "現在のプレーヤーを開く", volume: "システム音量", muted: "ミュート", idleInfo: "アイドル情報", previousItem: "前の項目", nextItem: "次の項目", resumeCarousel: "ローテーションを再開", pauseCarousel: "ローテーションを一時停止", toggleFloating: "フローティングプレーヤーを切替", timer: "タイマー", remainingTime: "残り時間", startTimer: "タイマーを開始", addMinute: "1分追加", addFiveMinutes: "5分追加", pauseTimer: "タイマーを一時停止", resumeTimer: "タイマーを再開", cancelTimer: "タイマーをキャンセル",
    studioIntro: "アイランドの外観、再生、システム動作を設定します。", currentMusic: "現在の音楽", simulated: "シミュレーション", browserDemo: "ブラウザデモ", previewLabel: "白背景の Dynamic Island プレビュー", previewState: "プレビュー状態", compact: "収納", hover: "ホバー", expanded: "展開", hidden: "非表示", shoulderShort: "接続部", audioSpectrum: "6バンド・オーディオスペクトラム", systemDefault: "システム既定", islandLayout: "アイランドの配置", shape: "形状", shapeHint: "フローティングまたは iPhone X 風の画面端", floating: "フローティング", attached: "画面端", screenEdge: "画面の端", screenEdgeHint: "展開時も端に接続", floatingBackground: "フローティング画面の塗り", floatingBackgroundHint: "アルバムカバーに連動しない場合の色", useAlbumColor: "アルバムカバーの色に連動", useAlbumColorHint: "カバーの代表色から縦方向のグラデーションを作成", top: "上", right: "右", bottom: "下", left: "左", screenTop: "画面上部", screenRight: "画面右側", screenBottom: "画面下部", screenLeft: "画面左側", edgePosition: "端に沿った位置", center: "中央に表示", compactLength: "収納時の長さ", shoulder: "接続部の丸み", expandedRadius: "展開時の角丸", language: "言語", systemLanguage: "システム設定に従う", chinese: "简体中文", english: "English", japanese: "日本語", font: "フォント", appFont: "アプリ全体のフォント", fontHint: "Studio、アイランド、フローティングプレーヤーに適用されます。", mediaScene: "メディアシーン", noCover: "カバーなし", longTitle: "長いタイトル", followMusic: "現在の音楽を表示", spectrum: "スペクトラム", showSpectrum: "スペクトラムを表示", showSpectrumHint: "再生中に6本のバーをアニメーション表示", animationSource: "アニメーション元", animationSourceHint: "リアルタイム音声またはランダム", realtime: "音楽に連動", random: "ランダム", players: "プレーヤー", refreshPlayers: "プレーヤーを更新", playersHint: "チェックしたプレーヤーのみを上から優先して表示します。", select: "{name}を選択", playingNow: "再生中", detected: "検出済み", offline: "オフライン", moveUp: "上へ", moveDown: "下へ", noSessions: "Windows メディアセッションが見つかりません",
    idleContent: "プレーヤーがないとき", enableIdle: "アイドル情報を切替表示", enableIdleHint: "一致するプレーヤーがない場合のみ表示", interval: "切替間隔", seconds: "{value} 秒", idleInterval: "アイドル情報の切替間隔", enableItem: "{name}を有効化", customText: "カスタムテキスト", deleteCustom: "カスタムテキストを削除", addCustom: "テキスト・顔文字を追加", clock: "時刻", date: "日付", weather: "天気", network: "通信速度", cpu: "CPU", memory: "メモリ", battery: "バッテリー", weatherCity: "天気の都市", cityExample: "例：東京", searchCity: "都市を検索", currentCity: "現在：{name}", weatherSource: "天気データ：Open-Meteo", searching: "検索中…", noCity: "一致する都市がありません", weatherFailed: "都市を検索できません。ネットワークを確認してください。", citySaved: "都市を保存しました",
    mediaFeatures: "メディア拡張", hdCover: "高解像度カバー", hdCoverHint: "鮮明なアルバムカバーを検索してキャッシュ", mvPlayback: "30秒 MV ループ", mvPlaybackHint: "Apple Music のプレビューを検索し、フローティング画面で無音ループ再生", appBehavior: "アプリの動作", alwaysOnTop: "常に最前面", alwaysOnTopHint: "アイランドを作業画面の上に表示", autoStart: "スタートアップ起動", autoStartHint: "Windows サインイン後に自動実行", monitor: "ディスプレイ", primaryMonitor: "メインディスプレイ", capture: "キャプチャとプライバシー", captureHint: "両方の画面に適用され、キャプチャ終了後に自動復帰します。", hideScreenshot: "スクリーンショット中は非表示", hideScreenshotHint: "Print Screen と Win + Shift + S に対応", hideRecording: "録画中は非表示", hideRecordingHint: "Windows のコンテンツ保護で録画から除外", hideFullscreen: "全画面ゲーム中は非表示", hideFullscreenHint: "ボーダーレス全画面を検出すると端へ収納", hideShare: "画面共有中は非表示", hideShareHint: "Windows のコンテンツ保護で共有画面から除外", tools: "ツール", openFloating: "フローティングプレーヤーを開く", resetFloating: "フローティング画面をリセット", clearCache: "画像・MVキャッシュを消去", clearing: "消去中…", cacheCleared: "画像・MVキャッシュを消去しました", clearFailed: "キャッシュを消去できません。もう一度お試しください。",
    featureTools: "機能ボタン", featureToolsHint: "展開時に表示するツールを選択します。", floatingTool: "フローティングプレーヤー", volumeTool: "システム音量", timerTool: "タイマー",
  },
} as const;

export type TranslationKey = keyof typeof translations["zh-CN"];

export function resolveLocale(preference: AppLanguage = "system"): ResolvedLocale {
  const raw = preference === "system"
    ? (typeof navigator === "undefined" ? "zh-CN" : navigator.language)
    : preference;
  const normalized = raw.toLowerCase();
  if (normalized.startsWith("ja")) return "ja";
  if (normalized.startsWith("en")) return "en";
  return "zh-CN";
}

export const locale = writable<ResolvedLocale>(resolveLocale());

export function setLocale(preference: AppLanguage = "system") {
  const resolved = resolveLocale(preference);
  locale.set(resolved);
  if (typeof document !== "undefined") document.documentElement.lang = resolved;
}

export function translate(key: TranslationKey, values: Record<string, string | number> = {}, selected?: ResolvedLocale) {
  const active = selected ?? resolveLocale();
  let result: string = translations[active][key] ?? translations["zh-CN"][key];
  for (const [name, value] of Object.entries(values)) result = result.replaceAll(`{${name}}`, String(value));
  return result;
}
